### ISSUE TITLE
Functions inside methods and this variable

### ISSUE THREAD

**Issue by rpora** [bmkmanoj/js-by-examples#4]
Hi there!
Always good to see people wanting to help others! And it's a nice little collection :) .

However, there is a little misinterpretation concerning [Functions inside methods and this variable](https://github.com/bmkmanoj/js-by-examples/blob/master/examples/functions_inside_methods_and_this_variable.md,) and in this particular case, in a forEach function, there is no need to 'hard bind' any context.

The function in `//1` is the callback of a forEach loop function. 
A forEach function (Array.prototype.forEach) can take 2 arguments even if the second, the "this" argument, is somewhat less known. See [Array.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)

The snippet

``` js
...
this.myNickNames.forEach(
   function (nickName) {  // 1
    console.log(this.myName +' is also known as '+ nickName);  // 2
   }.bind(this)
);
...
```

could be replaced with 

``` js
...
this.myNickNames.forEach(
   function (nickName) { console.log(this.myName +' is also known as '+ nickName); }, 
   this  // 2nd arg
);
...
```

How that's working? Let's try to build a minimal custom forEach function :

``` js
function forEach(array, callback, thisArg) {

  var length = array.length;
  var i = 0;

  for(i; i< length; i++){

    // Here, a forEach function applies the callback to thisArg
    callback.apply(thisArg, [array[i], i, array]);  
  }
}
```

So, I see a lot of people using `var self = this`  statements when using foreach, map and others arrays manipulation functions, and that's not necessary. 

And even better, we have now arrows functions with es2015.
Your snippet could be rewritten like this

``` js
...
this.myNickNames.forEach( 
   nickName =>  console.log(this.myName +' is also known as '+ nickName);  // Yeah!
);
...
```

That's all. Hope it can be useful!
And happy Js coding! ;)

**Comment by bmkmanoj** [comment]
Thanks @rpora for the suggestion. Would you like to create a pull request with these changes?

**Comment by timotius02** [comment]
Would it be better for this lesson to include all 3 examples (bind, cache, and pass 'this' directly) instead of replacing them?

**Comment by bhanu09** [comment]
Thanks @rpora  for the suggestion. I have used your example and updated the file.
